 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:3003/ (Press CTRL+C to quit)
10.244.122.29 - - [03/Jul/2016 13:23:22] "GET /write-message?message=http://www.cponeill.com%20-%20cponeill HTTP/1.1" 402 -
[2016-07-03 13:23:23,693] ERROR in app: Exception on /write-message [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/two1/bitserv/flask/decorator.py", line 104, in _fn
    return fn(*fn_args, **fn_kwargs)
  File "notary-server.py", line 49, in write_message
    raise Exception('No UTXOs available to pay for the transaction.')
Exception: No UTXOs available to pay for the transaction.
10.244.122.29 - - [03/Jul/2016 13:23:23] "GET /write-message?message=http://www.cponeill.com%20-%20cponeill HTTP/1.1" 500 -
 * Running on http://0.0.0.0:3003/ (Press CTRL+C to quit)
10.244.107.98 - - [05/Jul/2016 23:54:03] "GET /write-message?message=648a6a6ffffdaa0badb23b8baf90b6168dd16b3a HTTP/1.1" 402 -
10.244.107.98 - - [05/Jul/2016 23:54:04] "GET /write-message?message=648a6a6ffffdaa0badb23b8baf90b6168dd16b3a HTTP/1.1" 200 -
